section .data
    global about_content
    global about_content_end

    about_content:
        db "<!DOCTYPE html>"
        db "<html lang='en'>"
        db "<head>"
        db "    <meta charset='UTF-8'>"
        db "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        db "    <title>Wira Rajendra - Fullstack Developer</title>"
        db "    <style>"
        db "        :root {"
        db "            --primary-color: #2c3e50;"
        db "            --secondary-color: #34495e;"
        db "            --accent-color: #3498db;"
        db "            --text-color: #333;"
        db "            --background-color: #ecf0f1;"
        db "        }"
        db "        body {"
        db "            font-family: 'Roboto', Arial, sans-serif;"
        db "            line-height: 1.6;"
        db "            color: var(--text-color);"
        db "            background-color: var(--background-color);"
        db "            margin: 0;"
        db "            padding: 0;"
        db "        }"
        db "        .container {"
        db "            max-width: 900px;"
        db "            margin: 0 auto;"
        db "            padding: 2rem;"
        db "        }"
        db "        header {"
        db "            background-color: var(--primary-color);"
        db "            color: #fff;"
        db "            text-align: center;"
        db "            padding: 2rem 0;"
        db "        }"
        db "        h1, h2, h3 {"
        db "            color: var(--primary-color);"
        db "        }"
        db "        .section {"
        db "            background: #fff;"
        db "            margin: 1rem 0;"
        db "            padding: 1.5rem;"
        db "            border-radius: 8px;"
        db "            box-shadow: 0 4px 6px rgba(0,0,0,0.1);"
        db "        }"
        db "        .skills {"
        db "            display: flex;"
        db "            flex-wrap: wrap;"
        db "            gap: 0.5rem;"
        db "        }"
        db "        .skill {"
        db "            background: var(--secondary-color);"
        db "            color: #fff;"
        db "            padding: 0.5rem 1rem;"
        db "            border-radius: 20px;"
        db "            font-size: 0.9rem;"
        db "        }"
        db "        .experience-item {"
        db "            margin-bottom: 1.5rem;"
        db "        }"
        db "        .experience-title {"
        db "            font-weight: bold;"
        db "            color: var(--accent-color);"
        db "        }"
        db "        .experience-date {"
        db "            font-style: italic;"
        db "            color: #777;"
        db "        }"
        db "        footer {"
        db "            background: var(--primary-color);"
        db "            color: #fff;"
        db "            text-align: center;"
        db "            padding: 1rem;"
        db "            margin-top: 2rem;"
        db "        }"
        db "        a {"
        db "            color: var(--accent-color);"
        db "            text-decoration: none;"
        db "        }"
        db "        a:hover {"
        db "            text-decoration: underline;"
        db "        }"
        db "        @media screen and (max-width: 768px) {"
        db "            .container {"
        db "                padding: 1rem;"
        db "            }"
        db "        }"
        db "    </style>"
        db "</head>"
        db "<body>"
        db "    <header>"
        db "        <h1>Wira Rajendra</h1>"
        db "        <p>Fullstack Developer</p>"
        db "        <p>Email: wira@lsw.ink | <a href='https://github.com/wweziza' style='color: #fff;'>GitHub</a></p>"
        db "        <p>Yogyakarta, Indonesia</p>"
        db "    </header>"
        db "    <div class='container'>"
        db "        <div class='section'>"
        db "            <h2>Professional Summary</h2>"
        db "            <p>Innovative Fullstack Developer with a robust foundation in web and game development, complemented by a deep appreciation for assembly language. My technological journey is propelled by strong JavaScript proficiency and a keen interest in reverse engineering. Demonstrated expertise in managing complex projects, navigating both high-level and low-level programming challenges, and continuously pushing the boundaries of technological possibilities.</p>"
        db "        </div>"
        db "        <div class='section'>"
        db "            <h2>Professional Experience</h2>"
        db "            <div class='experience-item'>"
        db "                <p class='experience-title'>Fullstack Developer at Anugrah Javan Asia</p>"
        db "                <p class='experience-date'>October 2022 - July 2023</p>"
        db "                <ul>"
        db "                    <li>Maintained systems responsible for thousands of monthly transactions for a nickel importer company.</li>"
        db "                    <li>Implemented daily client database backup systems.</li>"
        db "                    <li>Utilized CI and Laravel frameworks for efficient development.</li>"
        db "                </ul>"
        db "            </div>"
        db "            <div class='experience-item'>"
        db "                <p class='experience-title'>Epic Games Internship</p>"
        db "                <p class='experience-date'>July 2024 - September 2024</p>"
        db "                <ul>"
        db "                    <li>Received comprehensive training in Web Development, Game Development, and IoT from the Epic Games development team.</li>"
        db "                    <li>Worked extensively with the Unreal Engine SDK.</li>"
        db "                    <li>Completed various problem-solving tasks using C++ and the Verse Programming Language.</li>"
        db "                </ul>"
        db "            </div>"
        db "            <div class='experience-item'>"
        db "                <p class='experience-title'>Project Management at LSW</p>"
        db "                <p class='experience-date'>2022 - Present</p>"
        db "                <ul>"
        db "                    <li>Manage a popular gaming server, enhancing community engagement.</li>"
        db "                    <li>Oversee comprehensive website development, including backend and frontend.</li>"
        db "                    <li>Develop and maintain gamemode written in Pawn (C++-like language).</li>"
        db "                    <li>Responsible for a database of nearly 50,000 client users.</li>"
        db "                    <li>Implemented Midtrans payment gateway, integrated with gamemode and website.</li>"
        db "                    <li>Developed and maintain a Discord.js bot for effective community moderation.</li>"
        db "                </ul>"
        db "            </div>"
        db "        </div>"
        db "        <div class='section'>"
        db "            <h2>Education</h2>"
        db "            <p>Binus University (September 2024) - Past Recognized Study in Computer Science</p>"
        db "        </div>"
        db "        <div class='section'>"
        db "            <h2>Technical Skills</h2>"
        db "            <div class='skills'>"
        db "                <span class='skill'>JavaScript</span>"
        db "                <span class='skill'>TypeScript</span>"
        db "                <span class='skill'>React</span>"
        db "                <span class='skill'>Node.js</span>"
        db "                <span class='skill'>Express.js</span>"
        db "                <span class='skill'>Next.js</span>"
        db "                <span class='skill'>PHP</span>"
        db "                <span class='skill'>Python</span>"
        db "                <span class='skill'>C++</span>"
        db "                <span class='skill'>Assembly</span>"
        db "                <span class='skill'>SQL</span>"
        db "                <span class='skill'>MongoDB</span>"
        db "                <span class='skill'>Git</span>"
        db "                <span class='skill'>RESTful APIs</span>"
        db "            </div>"
        db "        </div>"
        db "        <div class='section'>"
        db "            <h2>Certifications</h2>"
        db "            <ul>"
        db "                <li><a href='https://cs50.harvard.edu/certificates/32ac8ffb-5275-4c7e-9529-e37068ee3e95' target='_blank'>Harvard CS50: Introduction to Computer Science (September 2024)</a></li>"
        db "                <li><a href='https://www.freecodecamp.org/certification/weziza/front-end-development-libraries' target='_blank'>FreeCodeCamp.org Frontend Development Libraries (July 2024)</a></li>"
        db "                <li><a href='https://www.hackerrank.com/certificates/fullstack-developer' target='_blank'>HackerRank Fullstack Developer Certification (September 2024)</a></li>"
        db "            </ul>"
        db "        </div>"
        db "        <div class='section'>"
        db "            <h2>Notable Projects</h2>"
        db "            <h3>Electoral Elections System</h3>"
        db "            <p>Prototype electoral system developed for KPU (Komisi Pemilihan Umum)</p>"
        db "            <ul>"
        db "                <li>Efficiently handled nearly 1 billion data entries.</li>"
        db "                <li>Developed a responsive application with potential for mobile porting using Flutter.</li>"
        db "                <li>Integrated both MySQL and NoSQL databases for optimal performance.</li>"
        db "            </ul>"
        db "            <h3>LSW Gaming Platform</h3>"
        db "            <ul>"
        db "                <li>Developed a Discord.js bot integrated with payment gateway and backend systems.</li>"
        db "                <li>Created an extensive gamemode written in Pawn (100,000+ lines of code).</li>"
        db "                <li>Built a responsive website using Next.js (<a href='https://lsrp.world'>https://lsrp.world</a>) offering features such as password changes, ticketing, and character customization.</li>"
        db "                <li>Implemented MySQL database integration across all LSW ecosystems.</li>"
        db "            </ul>"
        db "            <h3>LSW.ink</h3>"
        db "            <p>Developed a link shortener and link.tree-like service tailored for streamers.</p>"
        db "            <h3>Personal Portfolio</h3>"
        db "            <p>Created a unique <a href='http://asm.lsw.ink'>personal portfolio</a> built entirely in Assembly x86.</p>"
        db "            <h3>Developer Tools</h3>"
        db "            <ul>"
        db "                <li>Sequientaldw: Python-based web scraping tool</li>"
        db "                <li>asm-http: HTTP server built using Assembly</li>"
        db "                <li>asm-encryption: Assembly-based encryption tool using XOR Cipher</li>"
        db "                <li>Jiro: Feature-rich Discord.js bot for LSW</li>"
        db "                <li>FiveM: Custom framework developed in Lua</li>"
        db "            </ul>"
        db "            <p>For more projects, please visit <a href='https://github.com/wweziza'>my GitHub repositories</a>.</p>"
        db "        </div>"
        db "    </div>"
        db "    <footer>"
        db "        <p>&copy; 2024 Wira Rajendra. This website is proudly built with <a href='https://github.com/wweziza/asm-http' style='color: #fff;'>x86 assembly</a>.</p>"
        db "    </footer>"
        db "</body>"
        db "</html>", 0
    about_content_end: