section .data
    global about_content

    about_content:
     db "<html><head>"
                   db "<title>Wira Rajendra - Fullstack Developer</title>"
                   db "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
                   db "<style>"
                   db "body {"
                   db "    font-family: Arial, sans-serif;"
                   db "    line-height: 1.6;"
                   db "    margin: 0;"
                   db "    padding: 0;"
                   db "    background-color: #f4f4f4;"
                   db "    color: #333;"
                   db "}"
                   db "header {"
                   db "    background-color: #35424a;"
                   db "    color: #ffffff;"
                   db "    padding: 1rem;"
                   db "    text-align: center;"
                   db "}"
                   db ".container {"
                   db "    width: 60%;"
                   db "    margin: auto;"
                   db "    overflow: hidden;"
                   db "    padding: 1rem;"
                   db "}"
                   db "@media screen and (max-width: 768px) {"
                   db "  .container {"
                   db "      width: 95%;"
                   db "      padding: 0.5rem;"
                   db "  }"
                   db "}"
                   db ".section {"
                   db "    background: #fff;"
                   db "    margin: 1rem 0;"
                   db "    padding: 1rem;"
                   db "    border-radius: 5px;"
                   db "    box-shadow: 0 2px 5px rgba(0,0,0,0.1);"
                   db "}"
                   db "h2 {"
                   db "    color: #35424a;"
                   db "}"
                   db ".skills {"
                   db "    display: flex;"
                   db "    flex-wrap: wrap;"
                   db "    gap: 0.5rem;"
                   db "}"
                   db ".skill {"
                   db "    background: #35424a;"
                   db "    color: #fff;"
                   db "    padding: 0.5rem;"
                   db "    border-radius: 5px;"
                   db "    font-size: 0.9rem;"
                   db "}"
                   db "footer {"
                   db "    background: #35424a;"
                   db "    color: #fff;"
                   db "    text-align: center;"
                   db "    padding: 1rem;"
                   db "    position: relative;"
                   db "    bottom: 0;"
                   db "    width: 100%;"
                   db "}"
                   db "</style>"
                   db "</head><body>"
                   db "<header>"
                   db "<h1>Wira Rajendra</h1>"
                   db "<p>Fullstack Developer</p>"
                   db "<p>Email: wira@lsw.ink | <a href='https://github.com/wweziza' style='color: #fff;'>GitHub</a></p>"
                   db "<p>Yogyakarta, Indonesia</p>"
                   db "</header>"
                   db "<div class='container'>"
                   db "<div class='section'>"
                   db "<h2>Summary</h2>"
                   db "<p>As a passionate Fullstack Developer, I combine a robust foundation in web and game development with a deep appreciation for assembly language. "
                   db "My journey through technology is fueled by a strong proficiency in JavaScript and a keen interest in reverse engineering.</p>"
                   db "</div>"
                   db "</div>"
                   db "</body></html>", 0
