section .data
    global index_content
    global index_content_end

index_content:
    db "<html><head>"
    db "<meta charset='UTF-8'>"
    db "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    db "<title>Assembly-Built Portfolio</title>"
    db "<style>"
    db "@keyframes fadeIn {"
    db "    from { opacity: 0; }"
    db "    to { opacity: 1; }"
    db "}"
    db "@keyframes slideIn {"
    db "    from { transform: translateY(20px); opacity: 0; }"
    db "    to { transform: translateY(0); opacity: 1; }"
    db "}"
    db "body {"
    db "    background-color: #1f1f1f;"
    db "    color: #e0e0e0;"
    db "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
    db "    text-align: center;"
    db "    margin: 0;"
    db "    padding: 0;"
    db "    display: flex;"
    db "    flex-direction: column;"
    db "    justify-content: center;"
    db "    align-items: center;"
    db "    min-height: 100vh;"
    db "}"
    db ".container {"
    db "    max-width: 800px;"
    db "    padding: 20px;"
    db "    animation: fadeIn 1s ease-out;"
    db "}"
    db "h1 {"
    db "    color: #bb86fc;"
    db "    font-size: 2.5em;"
    db "    margin-bottom: 20px;"
    db "    animation: slideIn 1s ease-out;"
    db "}"
    db "p {"
    db "    font-size: 18px;"
    db "    line-height: 1.6;"
    db "    margin-bottom: 30px;"
    db "    animation: slideIn 1s ease-out 0.2s backwards;"
    db "}"
    db ".highlight {"
    db "    color: #03dac6;"
    db "    font-weight: bold;"
    db "}"
    db ".btn {"
    db "    display: inline-block;"
    db "    background-color: #bb86fc;"
    db "    color: #1f1f1f;"
    db "    text-decoration: none;"
    db "    font-weight: bold;"
    db "    padding: 12px 24px;"
    db "    border-radius: 4px;"
    db "    transition: all 0.3s ease;"
    db "    animation: slideIn 1s ease-out 0.4s backwards;"
    db "}"
    db ".btn:hover {"
    db "    background-color: #03dac6;"
    db "    transform: translateY(-3px);"
    db "    box-shadow: 0 4px 8px rgba(3, 218, 198, 0.3);"
    db "}"
    db ".skills {"
    db "    display: flex;"
    db "    justify-content: center;"
    db "    flex-wrap: wrap;"
    db "    gap: 10px;"
    db "    margin-top: 30px;"
    db "    animation: fadeIn 1s ease-out 0.6s backwards;"
    db "}"
    db ".skill {"
    db "    background-color: #2f2f2f;"
    db "    color: #03dac6;"
    db "    padding: 8px 16px;"
    db "    border-radius: 20px;"
    db "    font-size: 14px;"
    db "}"
    db ".open-source {"
    db "    margin-top: 40px;"
    db "    font-style: italic;"
    db "    animation: fadeIn 1s ease-out 0.8s backwards;"
    db "}"
    db ".open-source a {"
    db "    color: #03dac6;"
    db "    text-decoration: none;"
    db "}"
    db ".open-source a:hover {"
    db "    text-decoration: underline;"
    db "}"
    db "</style>"
    db "</head><body>"
    db "<div class='container'>"
    db "<h1>Welcome to Wira's Portfolio Website</h1>"
    db "<p>Experience the power of low-level programming in web development. "
    db "This entire website is proudly built using <span class='highlight'>assembly language</span>!</p>"
    db "<a href='/about' class='btn'>View My Portfolio</a>"
    db "<div class='skills'>"
    db "    <span class='skill'>Assembly</span>"
    db "    <span class='skill'>Low-level Programming</span>"
    db "    <span class='skill'>Web Development</span>"
    db "    <span class='skill'>This not something called Innovation, but yeah assembly.</span>"
    db "</div>"
    db "<p class='open-source'>Proud of this project? It's open source! "
    db "Check out the code <a href='https://github.com/wweziza/personal-portfolio' target='_blank'>here</a>.</p>"
    db "</div>"
    db "</body></html>", 0
index_content_end: