.386
.model flat, stdcall
option casemap:none

.data
PUBLIC index_content
index_content db "<html><head>"
              db "<title>Wira Rajendra - Fullstack Developer</title>"
              db "<style>"
              db "body {"
              db "    font-family: Arial, sans-serif;"
              db "    line-height: 1.6;"
              db "    margin: 0;"
              db "    padding: 0;"
              db "    background-color: #f4f4f4;"
              db "    color: #333;"
              db "}"
              db "header {"
              db "    background-color: #35424a;"
              db "    color: #ffffff;"
              db "    padding: 1rem;"
              db "    text-align: center;"
              db "}"
              db ".container {"
              db "    width: 40%;"
              db "    margin: auto;"
              db "    overflow: hidden;"
              db "    padding: 1rem;"
              db "}"
              db "@media screen and (max-width: 768px) {"  
              db "  .container {"
              db "      width: 70%;"
              db "      padding: 0.5rem;"
              db "  }"
              db "}"
              db ".section {"
              db "    background: #fff;"
              db "    margin: 1rem 0;"
              db "    padding: 1rem;"
              db "    border-radius: 5px;"
              db "    box-shadow: 0 2px 5px rgba(0,0,0,0.1);"
              db "}"
              db "h2 {"
              db "    color: #35424a;"
              db "}"
              db ".skills {"
              db "    display: flex;"
              db "    flex-wrap: wrap;"
              db "    gap: 0.5rem;"
              db "}"
              db ".skill {"
              db "    background: #35424a;"
              db "    color: #fff;"
              db "    padding: 0.5rem;"
              db "    border-radius: 5px;"
              db "    font-size: 0.9rem;"
              db "}"
              db "footer {"
              db "    background: #35424a;"
              db "    color: #fff;"
              db "    text-align: center;"
              db "    padding: 1rem;"
              db "    position: relative;"
              db "    bottom: 0;"
              db "    width: 100%;"
              db "}"
              db "</style>"
              db "</head><body>"
              db "<header>"
              db "<h1>Wira Rajendra</h1>"
              db "<p>Fullstack Developer</p>"
              db "<p>Email: wira@lsw.ink | <a href='https://github.com/wweziza' style='color: #fff;'>GitHub</a></p>"
              db "<p>Yogyakarta, Indonesia</p>"
              db "</header>"
              db "<div class='container'>"
              db "<div class='section'>"
              db "<h2>Summary</h2>"
              db "<p>Experienced Fullstack Developer with a strong background in web development, game development, and project management. Proficient in a wide range of programming languages and technologies.</p>"
              db "</div>"
              db "<div class='section'>"
              db "<h2>Experience</h2>"
              db "<h3>Fullstack Developer at Anugrah Javan Asia (Oct 2022 - July 2023)</h3>"
              db "<p>Worked for a nickel importer company, maintaining systems responsible for thousands of monthly transactions, including daily client database backups.</p>"
              db "<ul>"
              db "<li>Responsible for website and database with almost hundred transaction every day.</li>"
              db "<li>Daily backups systems and database.</li>"
              db "<li>Worked with CI and Laravel.</li>"
              db "</ul>"
              db "<h3>Epic Games Internship (July 2024 - Sept 2024)</h3>"
              db "<p>Paid internship where I was trained by the development team in Web Dev, Game Dev, and IoT.</p>"
              db "<ul>"
              db "<li>Worked with the Unreal Engine SDK</li>"
              db "<li>Complete various task given by TL such as problem solving with C++.</li>"
              db "<li>Various task include learning with Verse Programming Language.</li>"
              db "</ul>"
              db "<h3>Project Management at LSW (2022 - Ongoing)</h3>"
              db "<ul>"
              db "<li>Managing a fun gaming server that brings joy to the community.</li>"
              db "<li>Handling website, backend, and frontend development.</li>"
              db "<li>Working with gamemode written in Pawn (C++-like language).</li>"
              db "<li>Responsible for almost 50k client database users.</li>"
              db "<li>Implemented payment gateway with Midtrans, integrated with gamemode and website.</li>"
              db "<li>Developed and maintain a Discord.js bot for community moderation.</li>"
              db "</ul>"
              db "</div>"
              db "<div class='section'>"
              db "<h2>Education</h2>"
              db "<p>Binus University (Sept 2024) - Past Recognized Study in Computer Science</p>"
              db "</div>"
              db "<div class='section'>"
              db "<h2>Skills</h2>"
              db "<div class='skills'>"
              db "<span class='skill'>JavaScript</span>"
              db "<span class='skill'>CSS</span>"
              db "<span class='skill'>GIT</span>"
              db "<span class='skill'>TypeScript</span>"
              db "<span class='skill'>Python</span>"
              db "<span class='skill'>Next.js</span>"
              db "<span class='skill'>SQL</span>"
              db "<span class='skill'>Node.js</span>"
              db "<span class='skill'>Express.js</span>"
              db "<span class='skill'>MongoDB</span>"
              db "<span class='skill'>NoSQL</span>"
              db "<span class='skill'>C++</span>"
              db "<span class='skill'>Assembly</span>"
              db "</div>"
              db "</div>"
              db "<div class='section'>"
              db "<h2>Certifications</h2>"
              db "<ul>"
              db "<li>Harvard Computer Science (Sept 2024)</li>"
              db "<li>FreeCodeCamp.org Frontend Developer (July 2024)</li>"
              db "<li>HackerRank Fullstack Developer (Sept 2024)</li>"
              db "</ul>"
              db "</div>"
              db "<div class='section'>"
              db "<h2>Projects</h2>"
              db "<h3>Electoral Elections</h3>"
              db "<p>Prototype of electoral elections for KPU (Komisi Pemilihan Umum)</p>"
              db "<ul>"
              db "<li>The apps handle smoothly almost 1 bilions data in it.</li>"
              db "<li>Responsive apps possible to port to mobile with Flutter</li>"
              db "<li>MySQL or NoSQL database integration</li>"
              db "</ul>"
              db "<h3>LSW</h3>"
              db "<ul>"
              db "<li>Discord.js bot integrated with payment gateway and backend</li>"
              db "<li>Gamemode written in Pawn (100,000 lines of code)</li>"
              db "<li>Responsive website built with Next.js (https://lsrp.world)</li>"
              db "<li>MySQL database integration across all LSW ecosystems</li>"
              db "</ul>"
              db "<h3>LSW.ink</h3>"
              db "<p>Link shortener and link.tree-like service for streamers</p>"
              db "<h3>Portfolio</h3>"
              db "<p>Personal portfolio built in Assembly x86</p>"
              db "<h3>Tools</h3>"
              db "<ul>"
              db "<li>Sequientaldw: Web scraping tool in Python</li>"
              db "<li>asm-http: HTTP server built in Assembly</li>"
              db "<li>asm-encryption: Assembly encryption using XOR Cipher</li>"
              db "<li>Jiro: Discord.js bot for LSW with various features</li>"
              db "<li>FiveM framework built in Lua</li>"
              db "</ul>"
              db "<p>More projects available at <a href='https://github.com/wweziza'>https://github.com/wweziza</a></p>"
              db "</div>"
              db "</div>"
              db "<footer>"
              db "<p>This website is built with Assembly. Check out the code: <a href='https://github.com/wweziza/asm-http' style='color: #fff;'>asm-http</a></p>"
              db "</footer>"
              db "</body></html>", 0

.code

end